# Generated by Django 5.2 on 2025-05-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTCMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('main_ingredients', models.TextField()),
                ('symptom', models.CharField(max_length=255)),
                ('dosage_by_age', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'otc_medicines',
                'managed': False,
            },
        ),
    ]
